services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
    networks:
      - lab-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: user
      MYSQL_PASSWORD: labor
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test:
        - CMD-SHELL
        - 'mysqladmin ping -h 127.0.0.1 -u -root -p"$$MYSQL_PASSWORD" --silent'
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s
    networks:
      - lab-network

  db-init:
    build: .
    command: ["python3", "reset_db.py"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - lab-network

volumes:
  db-data:

networks:
  lab-network:
