version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lab-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: labor 
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-plabpassword"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - lab-network

volumes:
  db-data:

networks:
  lab-network:
